# Generated by Django 2.2.7 on 2019-11-28 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('N', 'Normal'), ('M', 'Moderada'), ('H', 'Alta'), ('C', 'Crítica')], default='N', max_length=1)),
                ('contributors', models.ManyToManyField(blank=True, to='todomanager.ProjectUser')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta', to='todomanager.Label')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('was_concluded', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_concluded', models.DateTimeField(null=True)),
                ('concluded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todomanager.ProjectUser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='todomanager.Project')),
            ],
        ),
    ]
