# Generated by Django 2.2.5 on 2019-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
