# Generated by Django 2.2.7 on 2019-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0002_auto_20191126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_concluded',
            field=models.DateTimeField(null=True),
        ),
    ]
