# Generated by Django 2.2.7 on 2019-11-26 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0003_auto_20191126_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='concluded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todomanager.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(null=True, to='todomanager.ProjectUser'),
        ),
    ]
