# Generated by Django 2.2.7 on 2019-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0004_auto_20191126_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.ManyToManyField(related_name='atividades', to='todomanager.Activity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(to='todomanager.ProjectUser'),
        ),
    ]
