# Generated by Django 2.2.7 on 2019-11-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0005_auto_20191126_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='todomanager.ProjectUser'),
        ),
    ]
