# Generated by Django 2.2.7 on 2019-11-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0007_auto_20191126_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activities',
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='todomanager.Project'),
        ),
    ]
