# Generated by Django 2.2.7 on 2019-11-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0008_auto_20191126_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='todomanager.Project'),
        ),
    ]
