# Generated by Django 2.2.7 on 2019-11-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0009_auto_20191126_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todomanager.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to='todomanager.ProjectUser'),
        ),
    ]
