# Generated by Django 2.2.7 on 2019-11-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0010_auto_20191126_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='todomanager.Project'),
        ),
    ]
