# Generated by Django 2.2.7 on 2019-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0011_auto_20191126_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.ManyToManyField(related_name='atividades', to='todomanager.Activity'),
        ),
    ]
