# Generated by Django 2.2.5 on 2019-11-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0013_auto_20191126_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activities',
        ),
    ]
